"""add tekion_gl_accounts table

Revision ID: 2785f1cc97c9
Revises: 8e3968551fe4
Create Date: 2026-08-10 15:36:57.341608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2785f1cc97c9'
down_revision: Union[str, Sequence[str], None] = '8e3968551fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tekion_gl_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dealer_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('account_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('department_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dealer_id', 'account_id', name='uq_tekion_gl_dealer_account')
    )
    op.create_index(op.f('ix_tekion_gl_accounts_dealer_id'), 'tekion_gl_accounts', ['dealer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tekion_gl_accounts_dealer_id'), table_name='tekion_gl_accounts')
    op.drop_table('tekion_gl_accounts')
    # ### end Alembic commands ###
