"""add ro_number to documents

Revision ID: 5129f04c871e
Revises: 2785f1cc97c9
Create Date: 2026-08-10 16:57:09.420418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5129f04c871e'
down_revision: Union[str, Sequence[str], None] = '2785f1cc97c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('ro_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'ro_number')
    # ### end Alembic commands ###
