"""add documents table

Revision ID: 533a59fcd323
Revises: e6b1ff9c4403
Create Date: 2026-08-06 18:25:59.605228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '533a59fcd323'
down_revision: Union[str, Sequence[str], None] = 'e6b1ff9c4403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('dealership_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('po_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('po_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('exception_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_documents_dealership_name'), 'documents', ['dealership_name'], unique=False)
    op.create_index(op.f('ix_documents_po_type'), 'documents', ['po_type'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_vendor_name'), 'documents', ['vendor_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_vendor_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_po_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_dealership_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
