"""add gl_vendor_mappings table

Revision ID: 8e3968551fe4
Revises: 533a59fcd323
Create Date: 2026-08-07 16:26:14.432792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import uuid
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = '8e3968551fe4'
down_revision: Union[str, Sequence[str], None] = '533a59fcd323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gl_vendor_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('gl_account', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gl_vendor_mappings_vendor_name'), 'gl_vendor_mappings', ['vendor_name'], unique=True)

    # Seed master misc vendor-to-GL lookup table.
    gl_vendor_table = sa.table(
        "gl_vendor_mappings",
        sa.column("id", sa.Uuid),
        sa.column("vendor_name", sa.String),
        sa.column("gl_account", sa.String),
        sa.column("description", sa.String),
        sa.column("created_at", sa.DateTime),
    )
    now = datetime.now(timezone.utc)
    op.bulk_insert(gl_vendor_table, [
        {"id": str(uuid.uuid4()), "vendor_name": "ADVANCE AUTO PARTS", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "ILLINOIS RECOVERY GROUP", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "ILLINOIS TIRE RECYCLING", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "MCGARD", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "O'REILLY'S AUTO PARTS", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "O REILLY AUTO PARTS", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "OREILLYS AUTO PARTS", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "S&S AUTOMOTIVE", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "S AND S AUTOMOTIVE", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "TERRACE SUPPLY CO", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "WILDMAN FACILITY", "gl_account": "7193", "description": "Service Supplies & Small Tools", "created_at": now},
        {"id": str(uuid.uuid4()), "vendor_name": "DGO PREMIUM SERVICES", "gl_account": "7490", "description": "Outside Service", "created_at": now},
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gl_vendor_mappings_vendor_name'), table_name='gl_vendor_mappings')
    op.drop_table('gl_vendor_mappings')
    # ### end Alembic commands ###
