"""replace vendor_mappings seed with full Excel data

Revision ID: a1b2c3d4e5f6
Revises: 967da6cad2f9
Create Date: 2026-08-05 10:30:00.000000

"""
from typing import Sequence, Union
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, Sequence[str], None] = "967da6cad2f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Replace old seed with full vendor list from VENDOR LIST 2026.xlsx."""
    # Clear old seed data
    op.execute("DELETE FROM vendor_mappings")

    vendor_mappings_table = sa.table(
        "vendor_mappings",
        sa.column("id", sa.Uuid),
        sa.column("dealer_id", sa.String),
        sa.column("vendor_name", sa.String),
        sa.column("vendor_display_id", sa.String),
        sa.column("created_at", sa.DateTime),
    )
    now = datetime.now(timezone.utc)
    op.bulk_insert(vendor_mappings_table, [
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "CHICAGO WRAP", "vendor_display_id": "2275", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "1-800-RADIATOR & A/C", "vendor_display_id": "1708_806", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "A-1 SUBURBAN LOCK & KEY", "vendor_display_id": "1708_858", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "AARON GLASS", "vendor_display_id": "1708_4318", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ABC AUTOMOTIVE ELECTRONICS", "vendor_display_id": "1710_ABC", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ADVANCE AUTO PARTS", "vendor_display_id": "1708_304", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ADVANTAGE AUTO GLASS", "vendor_display_id": "1710_225", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ADVANTAGE AUTO GLASS & TRIM", "vendor_display_id": "ADVANTAGEAUTO", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "AER", "vendor_display_id": "1708_329", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "AER TECHNOLOGIES", "vendor_display_id": "1708_650", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "AIRE-MASTER OF SUBURBAN CHICAGOLAND", "vendor_display_id": "1810", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "AL PIEMONTE FORD", "vendor_display_id": "1708_343", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ALLOY WHEEL REPAIR", "vendor_display_id": "1708_864", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "AMERICAN WELDING & GAS INC", "vendor_display_id": "1708_741", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ARAMARK (REFRESHMENT SERVICE)", "vendor_display_id": "1708_795", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ARLINGTON ACURA", "vendor_display_id": "1708_179", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ARLINGTON HEIGHTS FORD", "vendor_display_id": "1708_302", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ARLINGTON NISSAN", "vendor_display_id": "1708_503", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "AUTO GLASS MASTERS", "vendor_display_id": "1708_331", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "BELMONT KOLMAR TOWING", "vendor_display_id": "2105", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "BNC QUALITY AUTOBODY SCHAUMBURG", "vendor_display_id": "1840", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "CARBIZZA.", "vendor_display_id": "1978", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "CARS TRANSPORT LOGISTICS", "vendor_display_id": "1711_CARSTOWING", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "CHICAGO PARTS AND SOUND", "vendor_display_id": "1708_305", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "CHICAGO WHEEL COVER", "vendor_display_id": "1708_865", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "CINTAS LOC #40K", "vendor_display_id": "1708_432", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "CINTAS LOC#40K", "vendor_display_id": "1708_CINTAS", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "COLLISION SERVICE CENTER", "vendor_display_id": "1708_792", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "DENT WIZARD", "vendor_display_id": "1708_463", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "DIGITAL COPIER SUPERCENTER", "vendor_display_id": "1708_DCS", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "DPS AUTOMOTIVE LLC", "vendor_display_id": "1708_757", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "EXCELL AUTOMOTIVE EQUIPMENT, INC.", "vendor_display_id": "1708_176", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "FACTORY MOTOR PARTS BIN 139107", "vendor_display_id": "1708_464", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "FOB EXCHANGE", "vendor_display_id": "2233", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "FORD ACCESSORIES OF CHICAGO", "vendor_display_id": "1708_1005", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "GARRYS AUTOMOTIVE RESTORATION INC", "vendor_display_id": "1703_763", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "GERBER COLLISION", "vendor_display_id": "1708_GERBER", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "GOLF MILL FORD", "vendor_display_id": "1708_307", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "GURNEE HYUNDAI", "vendor_display_id": "1708_414", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "GURNEE VOLKSWAGEN", "vendor_display_id": "1708_160", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "HAWK FORD OF CAROL STREAM", "vendor_display_id": "1919", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "HAWK FORD OF ST CHARLES", "vendor_display_id": "1708_369", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "HAWK PARTS WAREHOUSE", "vendor_display_id": "1777", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "HILLSIDE", "vendor_display_id": "2216", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "HILLSIDE TOWING", "vendor_display_id": "1708_439", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "HOPKINS FORD OF ELGIN", "vendor_display_id": "1708_313", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ILLINI AUTOLIFT & EQUIPMENT", "vendor_display_id": "1708_360", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ILLINOIS RECOVERY GROUP", "vendor_display_id": "1708_761", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ILLINOIS TIRE RECYCLING", "vendor_display_id": "1708_382", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "J-TEAM TOWING", "vendor_display_id": "2360", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "LEXUS OF ARLINGTON", "vendor_display_id": "1708_508", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "LKQ AUTO PARTS", "vendor_display_id": "1708_468", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "LOCKSMITH FOR YOU", "vendor_display_id": "1708_1757", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "MASTER HITCH", "vendor_display_id": "1708_429", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "MCGARD", "vendor_display_id": "1708_721", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "MERCEDES-BENZ OF HOFFMAN ESTATES", "vendor_display_id": "1708_350", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "MID-TOWN PETROLEUM ACQUISITION LLC", "vendor_display_id": "1895", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "MITA MOBILE SERVICES", "vendor_display_id": "1708_MITA", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "MORRISONS AUTO INC", "vendor_display_id": "1918", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "MOTOR WERKS", "vendor_display_id": "1708_704", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "MURGADO FORD OF CHICAGO", "vendor_display_id": "2750", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "NAPELTON SCHAMBURG MAZDA", "vendor_display_id": "1708_1059858", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "NAPLETON LINCOLN OF SCHAUMBURG", "vendor_display_id": "2330", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "NAPLETON SUBARU", "vendor_display_id": "1708_1115", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "NAPLETON''S SCHAUMBURG BUICK GMC", "vendor_display_id": "1708_220", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "NORTHWEST VOLTWAGON", "vendor_display_id": "1708_824", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "NORTON''S PLUMBING & SEWER SERVICE", "vendor_display_id": "1708_A", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "NORTONS SEWER SERVICE", "vendor_display_id": "1708_877", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "O''REILLY AUTO PARTS", "vendor_display_id": "1708_540", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "OAKBROOK TOYOTA", "vendor_display_id": "1708_437", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PATRICK BMW", "vendor_display_id": "1708_259", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PATRICK CADILLAC SAAB VOLVO", "vendor_display_id": "1708_517", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PATRICK HYUNDAI", "vendor_display_id": "1708_801", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PATRICK MINI", "vendor_display_id": "1704_702", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PATRICK VOLVO", "vendor_display_id": "1708_531", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PEPPER AUTO BODY", "vendor_display_id": "2529", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PHILLIPS AIR COMPRESSOR", "vendor_display_id": "1881", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PORSCHE BARRINGTON", "vendor_display_id": "1709_1009", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PRECISION AUTO RECONDITIONING", "vendor_display_id": "1708_1010", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PROGRAM ONE", "vendor_display_id": "1708_910", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "PURE WATER SYSTEMS OF CHICAGOLAND", "vendor_display_id": "1710_6", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "RELADYNE", "vendor_display_id": "2117", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "S&S AUTOMOTIVE INC", "vendor_display_id": "1718_20006", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SANDMAN PLUMBING", "vendor_display_id": "2315", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SCHAUMBURG BUICK GMC", "vendor_display_id": "1708_871", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SCHAUMBURG HONDA", "vendor_display_id": "1708_356", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SCHAUMBURG KIA", "vendor_display_id": "1708_535", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SCHAUMBURG TOYOTA", "vendor_display_id": "1708_353", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SECURE SOLUTIONS", "vendor_display_id": "1708_965", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SNAP-ON BUSINESS SOLUTIONS, INC.", "vendor_display_id": "1708_SNAPON", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SPEEDWAY AUTO PARTS LTD", "vendor_display_id": "2164", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SPRING ALIGN", "vendor_display_id": "1708_767", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SUBURBAN WHEEL COVER CO.", "vendor_display_id": "1708_357", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "SUPERIOR SOUND", "vendor_display_id": "1708_328", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "TERRACE SUPPLY", "vendor_display_id": "1708_436", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "TOP COVERAGE", "vendor_display_id": "1708_362", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "TSD RENTALS", "vendor_display_id": "2102", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "U.S UPFITTERS", "vendor_display_id": "2243", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ULINE", "vendor_display_id": "1708_ULINE", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "UNITED RADIO", "vendor_display_id": "1708_479", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "US AUTO FORCE", "vendor_display_id": "1708_416", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "VARSITY VENDING & COFFEE SERVICES", "vendor_display_id": "1708_315", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "VGP HOLDING LLC", "vendor_display_id": "1708_340", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "VINTAGE PARTS INC", "vendor_display_id": "1708_318", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "VITAL RECORDS CONTROL", "vendor_display_id": "1708_954", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "WEBMARC DOORS", "vendor_display_id": "1708_898", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "WICKSTROM FORD", "vendor_display_id": "1708_411", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "WILDMAN FACILITY SERVICES", "vendor_display_id": "2624", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "WOODFIELD LEXUS", "vendor_display_id": "1708_145", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "WOODFIELD NISSAN", "vendor_display_id": "1708_431", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "YOCKEY''S FRIENDLY FORD", "vendor_display_id": "1708_309", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ZEIGLER CHEVROLET", "vendor_display_id": "1707_493", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ZEIGLER CHEVROLET OF SCHAUMBURG", "vendor_display_id": "1708_539", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ZEIGLER CHRYSLER", "vendor_display_id": "2376", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ZEIGLER INFINITI OF HOFFMAN ESTATES", "vendor_display_id": "1708_868", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ZEIGLER LAND ROVER-JAGUAR", "vendor_display_id": "1708_1080", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1708", "vendor_name": "ZEIGLER OF SCHAUMBURG", "vendor_display_id": "1708_355", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "A-1 SUBURBAN LOCK", "vendor_display_id": "1710_512", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ABC AUTOMOTIVE ELECTRONICS", "vendor_display_id": "1710_ABC", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ADVANCE AUTO PARTS", "vendor_display_id": "1710_ADVANCE", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ARAMARK REFRESHMENT SERVICES", "vendor_display_id": "2241", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ARLINGTON ACURA", "vendor_display_id": "1710_191", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ARLINGTON KIA", "vendor_display_id": "1710_1400", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ARLINGTON NISSAN", "vendor_display_id": "1710_159", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "AUTO GLASS MASTERS", "vendor_display_id": "1710_450", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "AUTOZONE", "vendor_display_id": "1710_2211", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "BELMONT KOLMAR TOWING", "vendor_display_id": "2105", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "BERWYN KIA", "vendor_display_id": "1710_7050", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "CARBIZZA", "vendor_display_id": "1710_AUTOB", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "CASTLE CARS OF MCHENRY", "vendor_display_id": "1710_1107", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "CASTLE DOWNERS GROVE", "vendor_display_id": "1967", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "CASTLE OF DOWNERS GROVE", "vendor_display_id": "1710_2020", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "CASTLE VOLKSWAGEN", "vendor_display_id": "2365", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "CHICAGO PARTS & SOUND", "vendor_display_id": "1710_CPS", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "CHICAGO WHEEL SERVICE", "vendor_display_id": "1710_358", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "CINTAS", "vendor_display_id": "1710_107", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "CINTAS CORP", "vendor_display_id": "1710_CINTAS", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "CITY AUTO USED AUTO PARTS", "vendor_display_id": "1892", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "COLLISION SERVICE CENTER", "vendor_display_id": "1710_CSC", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "DENT WIZARD", "vendor_display_id": "1710_154", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "DGO PREMIUM SERVICES", "vendor_display_id": "1710_126", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "DIGITAL COPIER SUPERCENTER", "vendor_display_id": "1710_1462", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ETRONICS", "vendor_display_id": "1710_ETRONICS", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "EVERGREEN KIA", "vendor_display_id": "1710_4000", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "EXCELL AUTOMOTIVE EQUIPMENT", "vendor_display_id": "1710_7900", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "FOB EXCHANGE", "vendor_display_id": "2233", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "G.A.R.I.", "vendor_display_id": "1710_GARI", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "GENESIS OF SCHAUMBURG", "vendor_display_id": "2320", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "GERALD KIA", "vendor_display_id": "1710_1545", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "GERALD KIA OF MATTESON", "vendor_display_id": "2037", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "GS CLEANING SOLUTIONS INC", "vendor_display_id": "2691", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "GURNEE HYUNDAI", "vendor_display_id": "1710_648", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "GURNEE VOLKSWAGEN", "vendor_display_id": "1710_26", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "HILLSIDE AUTOBODY & SERVICES", "vendor_display_id": "1710_115", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ILLINI AUTOLIFT & EQUIP", "vendor_display_id": "1710_ILLINI", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ILLINOIS RECOVERY GROUP", "vendor_display_id": "1710_1119", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ILLINOIS TIRE RECYCLING", "vendor_display_id": "1710_386", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "KIA OF LINCOLNWOOD", "vendor_display_id": "1710_8477454360", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "LEXUS OF ARLINGTON", "vendor_display_id": "1710_508", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "LIBERTY AUTO PLAZA", "vendor_display_id": "1704_114P", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "LIBERTY KIA", "vendor_display_id": "1710_4858", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "LKQ STAR AUTO PARTS", "vendor_display_id": "1710_2101", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "MARTIN CHEVY", "vendor_display_id": "1710_5220", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "MASTER HITCH INC", "vendor_display_id": "1710_514", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "MCGRATH HIGHLAND PARK KIA", "vendor_display_id": "2131", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "MITA MOBILE SERVICES LLC", "vendor_display_id": "1710_MITA", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "MORRISONS AUTO INC", "vendor_display_id": "1710_6307", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "NAPA AUTO PARTS", "vendor_display_id": "2029", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "NAPLETON BUICK GMC", "vendor_display_id": "1710_252", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "NAPLETON HYUNDAI", "vendor_display_id": "2507", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "NAPLETON SCHAUMBURG SUBARU", "vendor_display_id": "1710_911", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "NAPLETON''S KIA OF ELMHURST", "vendor_display_id": "1710_319", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "OAKBROOK TOYOTA", "vendor_display_id": "1710_187", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "OPEL ENGINEERING CO", "vendor_display_id": "1710_OPEL", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "OREILLY AUTO PARTS", "vendor_display_id": "1710_182", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "PARTSTRADER LLC", "vendor_display_id": "1710_PARTSTRADER", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "PATRICK BMW", "vendor_display_id": "1710_352", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "PATRICK CADILLAC VOLVO SAAB", "vendor_display_id": "1710_350", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "PATRICK HYUNDAI", "vendor_display_id": "1710_150", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "PRECISION MOBILE WHEEL REPAIR", "vendor_display_id": "1710_641", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "PROFICIENT WINDOW CLEANING", "vendor_display_id": "1710_PROW", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "RAYMOND CHEVROLET KIA", "vendor_display_id": "2689", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "REDMONS TOWING", "vendor_display_id": "1710_104", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "S & S AUTO INC", "vendor_display_id": "1710_855", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "SCHAUMBURG FORD", "vendor_display_id": "1710_157", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "SCHAUMBURG HONDA AUTOMOBILES", "vendor_display_id": "1710_862", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "SCHAUMBURG TOYOTA", "vendor_display_id": "1710_863", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "SCOTT STEPHANSEN", "vendor_display_id": "1710_SS", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "SECURE SOLUTIONS, INC.", "vendor_display_id": "1710_257", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "SPEEDWAY AUTO PARTS LTD", "vendor_display_id": "2164", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "SUBURBAN WHEEL COVER", "vendor_display_id": "1710_576", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "SUPERGLASS WINDSHIELD REPAIR", "vendor_display_id": "1710_167", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "SUPERIOR SOUND", "vendor_display_id": "1710_869", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "TIRE RACK WHOLESALE", "vendor_display_id": "1702_7101", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "TOP COVERAGE", "vendor_display_id": "1710_918", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "TR WHOLESALE SOLUTIONS", "vendor_display_id": "1710_1001", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ULINE", "vendor_display_id": "1710_ULINE", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "USAUTOFORCE", "vendor_display_id": "1710_401", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "VARSITY VENDING", "vendor_display_id": "1710_153", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "VGP HOLDINGS LLC", "vendor_display_id": "1710_939", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "VITAL RECORDS CONTROL", "vendor_display_id": "1710_SHRED", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "WEBMARC DOORS", "vendor_display_id": "1710_WEBMARC", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "WILDMAN FACILITY SERVICES", "vendor_display_id": "2625", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "WILLOWBROOK FORD/KIA", "vendor_display_id": "1710_301", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "WINZER", "vendor_display_id": "1710_WINZER", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "WOLTER INC", "vendor_display_id": "2686", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "WOODFIELD LEXUS", "vendor_display_id": "1710_350E", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "WOODFIELD NISSAN", "vendor_display_id": "1710_1478", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ZEIGLER ALFA ROMEO", "vendor_display_id": "1710_ALFA", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ZEIGLER CHEVROLET", "vendor_display_id": "1710_8478828400", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ZEIGLER CHRYSLER", "vendor_display_id": "2376", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ZEIGLER CHRYSLER DODGE JEEP", "vendor_display_id": "1710_158", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ZEIGLER INFINITI", "vendor_display_id": "1710_1075", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ZEIGLER JAGUAR-LAND ROVER", "vendor_display_id": "2068", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ZEIGLER MERCEDES BENZ", "vendor_display_id": "1803", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1710", "vendor_name": "ZEIGLER MERCEDES-BENZ", "vendor_display_id": "1710_555", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ADVANCE AUTO PARTS", "vendor_display_id": "1707_160", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ADVANCED IMPRESSIONS", "vendor_display_id": "1707_338", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "AMERICA''S AUTO BODY", "vendor_display_id": "1707_83", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "AMP''D DESIGNS", "vendor_display_id": "1905", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ARAMARK REFRESHMENT SERVICE", "vendor_display_id": "1707_310", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ARLINGTON ACURA", "vendor_display_id": "1707_123", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ARLINGTON NISSAN", "vendor_display_id": "1707_127", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "AUTO GLASS MASTERS", "vendor_display_id": "1707_131", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "BESSLER AUTO PARTS-LOUISVILLE", "vendor_display_id": "1707_984", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "BIONIC AUTO PARTS", "vendor_display_id": "1707_76", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "BNC QUALITY AUTOBODY", "vendor_display_id": "1707_1007", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "BRILLIANCE HONDA", "vendor_display_id": "1707_29", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "BRITE-O-MATIC MANUFACTURING INC", "vendor_display_id": "1707_BRITE", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "CARBIZZA", "vendor_display_id": "1707_362", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "CASTLE VOLKSWAGEN", "vendor_display_id": "1707_207", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "CCC INTELLIGENT SOLUTIONS", "vendor_display_id": "1707_CCC", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "CHESSNUT PRODUCTS", "vendor_display_id": "1707_165", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "CINTAS CORPORATION", "vendor_display_id": "1707_499", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "CINTAS FIRE", "vendor_display_id": "1707_7813", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "CITY AUTO USED AUTO PARTS", "vendor_display_id": "1892", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "DENT WIZARD", "vendor_display_id": "1707_198", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "DGO PREMIUM", "vendor_display_id": "1707_960", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "DPS AUTOMOTIVE", "vendor_display_id": "1756", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ENTERPRISE RENT-A-CAR", "vendor_display_id": "1707_213", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ETRONICS, INC", "vendor_display_id": "1707_5090", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "EXCEL SPORTS WEAR", "vendor_display_id": "2279", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "FACTORY CLEANING EQUIPMENT", "vendor_display_id": "2383", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "FAST SIGNS OF SCHAUMBURG", "vendor_display_id": "1707_255", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "FASTBREAK", "vendor_display_id": "1758", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "FENIX PARTS CHICAGO", "vendor_display_id": "2484", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "G A R I", "vendor_display_id": "1707_231", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "GENESIS OF SCHAUMBURG", "vendor_display_id": "2320", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "GURNEE HYUNDAI-GURNEE VBOLKSWAGEN", "vendor_display_id": "1707_232", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "HILLSIDE", "vendor_display_id": "2216", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "HONDA ON GRAND", "vendor_display_id": "1707_370", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ILLINOIS RECOVERY GROUP INC", "vendor_display_id": "1707_222", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ILLINOIS TIRE RECYCLING", "vendor_display_id": "1707_191", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "INTERSTATE BATTERIES", "vendor_display_id": "1707_281", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "K&T AUTO SUPPLY", "vendor_display_id": "1707_450S", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "LEXUS OF ARLINGTON", "vendor_display_id": "1707_126", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "LISLE AUTO PLAZA", "vendor_display_id": "1707_321", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "MCGARD", "vendor_display_id": "1707_341", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "MCGRATH HONDA", "vendor_display_id": "1707_329", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "MITA MOBILE", "vendor_display_id": "1769", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "MOTORWERKS", "vendor_display_id": "1707_356", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "OAKBROOK TOYOTA", "vendor_display_id": "1707_471", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "OPEL AUTOMOTIVE", "vendor_display_id": "1707_364", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "OREILLYS AUTO PARTS", "vendor_display_id": "1707_9464", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "OVERALL PARTS SOLUTION, INC", "vendor_display_id": "1707_75103", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "PALO ALTO SPEEDOMETER", "vendor_display_id": "2151", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "PARTSTRADER LLC", "vendor_display_id": "1707_PARTSTRADER", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "PATRICK BMW", "vendor_display_id": "1707_388", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "PATRICK CADILLAC/SAAB/VOLVO", "vendor_display_id": "1707_389", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "PATRICK HYUNDAI", "vendor_display_id": "1707_436", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "PHILLIPS AIR COMPRESSOR", "vendor_display_id": "1881", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "PRECISION AUTO RECONDITIONING", "vendor_display_id": "1707_336", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "REDMON''S TOWING", "vendor_display_id": "1707_413", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "S&S AUTOMOTIVE", "vendor_display_id": "1707_461", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "SCHAUMBURG FORD", "vendor_display_id": "1707_985", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "SCHAUMBURG KIA", "vendor_display_id": "1707_68", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "SCHAUMBURG MAZDA", "vendor_display_id": "1707_568", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "SCHAUMBURG TOYOTA", "vendor_display_id": "1707_437", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "SECURE LOCKS", "vendor_display_id": "2265", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "SIGN*A*RAMA", "vendor_display_id": "1707_284", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "SPEEDGEAR", "vendor_display_id": "1707_446", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "STAPLES PROMOTIONAL PRODUCTS", "vendor_display_id": "1707_175", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "SUBARU OF SCHAUMBURG", "vendor_display_id": "1707_458", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "SUBURBAN WHEEL COVER CO", "vendor_display_id": "1707_1420", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "SUNBIT", "vendor_display_id": "2144", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "TERRACE SUPPLY CO", "vendor_display_id": "1707_464", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "THE TIRE RACK", "vendor_display_id": "1707_602", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "TOP COVERAGE", "vendor_display_id": "1707_470", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ULINE", "vendor_display_id": "2721", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "VALLEY HONDA", "vendor_display_id": "1707_484", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "VALVOLINE INC", "vendor_display_id": "1707_482", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "VARSITY VENDING & COFFEE SERVICE, LLC", "vendor_display_id": "1707_962", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "VENTUS AUTO GLASS INC", "vendor_display_id": "1707_6713", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "VINTAGE AUTO PARTS", "vendor_display_id": "1707_515", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "VITAL RECORDS CONTROL", "vendor_display_id": "1711_PROSHRED", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "WILDMAN FAS INDIANAPOLIS", "vendor_display_id": "2626", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "WINZER", "vendor_display_id": "1955", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "WOODFIELD ACURA", "vendor_display_id": "1707_492", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "WOODFIELD LEXUS", "vendor_display_id": "1707_495", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ZEIGLER ALFA ROMEO", "vendor_display_id": "1863", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ZEIGLER CHEVROLET", "vendor_display_id": "1707_493", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ZEIGLER MERCEDES-BENZ", "vendor_display_id": "1707_350", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1707", "vendor_name": "ZEIGLER OF SCHAUMBURG", "vendor_display_id": "1707_434", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "1-800-RADIATOR", "vendor_display_id": "1711_1800", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "ALLDATA", "vendor_display_id": "1711_ALLDATA", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "AMERICAN WELDING AND GAS", "vendor_display_id": "1711_AWG", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "ARLINGTON ACURA", "vendor_display_id": "1711_ACURA", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "ARLINGTON NISSAN", "vendor_display_id": "1711_ARLINGTON", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "AUDI WESTMONT", "vendor_display_id": "1711_137088", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "AUTO GLASS MASTERS", "vendor_display_id": "1711_5277", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "AUTO ZONE INC.", "vendor_display_id": "1711_AUTO", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "AUTOZONE INC", "vendor_display_id": "1722_10077", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "BALES LUMBER & SUPPLY", "vendor_display_id": "1711_5389", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "BILL KAY CHEVROLET", "vendor_display_id": "1711_5220", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "BILL KAY DOWNERS GROVE NISSAN", "vendor_display_id": "1711_5215", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "BILL KAY PONTIAC GMC", "vendor_display_id": "1711_5589", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "BIOSWEEP", "vendor_display_id": "1711_BIOSWEEP", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "BOB ROHRMAN TOYOTA", "vendor_display_id": "1711_701", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "BODY LANGUAGE,INC", "vendor_display_id": "1711_6985", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "BUTTREY RENTAL SERVICE INC", "vendor_display_id": "1711_5175", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "CARS TRANSPORT LOGISTICS", "vendor_display_id": "1711_CARSTOWING", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "CASTLE DOWNERS GROVE", "vendor_display_id": "1967", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "CERTIFIED TOWING INC", "vendor_display_id": "1711_5600", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "CHICAGO AUTO PROS DETAILING", "vendor_display_id": "1951", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "CHICAGO PARTS & SOUND LLC", "vendor_display_id": "1711_5185", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "CHICAGO WRAP", "vendor_display_id": "1711_CHICAGOWRAP", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "CINTAS CORPORATION", "vendor_display_id": "1711_5050", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "CINTAS FIRE PROTECTION", "vendor_display_id": "1711_CINTAS", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "COLLISION CRAFT", "vendor_display_id": "1711_7173", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "CONTINENTAL TOYOTA", "vendor_display_id": "1711_6003", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "CPC POWDER COATING & SAND BLASTING INC", "vendor_display_id": "1711_CPC", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "DENT WIZARD", "vendor_display_id": "1711_5396", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "ERNIE''S TOWING", "vendor_display_id": "1711_7000", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "GARRY''S AUTOMOTIVE RESTORATION INC", "vendor_display_id": "1711_5428", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "GERALD SUBARU OF NAPERVILLE", "vendor_display_id": "1711_5181", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "GRAINGER", "vendor_display_id": "1711_5323", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "GURNEE HYUNDAI", "vendor_display_id": "1711_52761", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "HERCULES SYSTEMS INC", "vendor_display_id": "2091", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "HONDA OF LISLE", "vendor_display_id": "1711_6004", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "ILLINI AUTOLIFT & EQUIPMENT, INC", "vendor_display_id": "1711_ILLINI", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "ILLINOIS RECOVERY GROUP", "vendor_display_id": "1711_IRG", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "ILLINOIS TIRE RECYCLING", "vendor_display_id": "1711_ITR", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "IMPERIAL AUTO SOLVENTS, INC.", "vendor_display_id": "1851", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "KEYSTONE", "vendor_display_id": "1711_KEYSTONE", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "LAUREL BMW", "vendor_display_id": "1711_6902", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "LKQ CORP (STAR)", "vendor_display_id": "1711_2700", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "LOMBARD TOYOTA", "vendor_display_id": "1711_6081", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "LST MECHANICAL LLC", "vendor_display_id": "1711_LST", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "MC GRATH ACURA", "vendor_display_id": "1711_5332", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "MC GRATH LEXUS", "vendor_display_id": "1711_5123", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "MCGRATH ELMHURST TOYOTA", "vendor_display_id": "1711_7345", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "MERCEDES BENZ OF WESTMONT", "vendor_display_id": "1711_6007", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "MIDAS AUTO SERVICE CENTER", "vendor_display_id": "1711_5588", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "MIDWEST AUTOBAHND", "vendor_display_id": "1711_MIDWEST", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "NAPA AUTO PARTS", "vendor_display_id": "1711_6028", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "OAKBROOK MECHANICAL SERVICES,INC", "vendor_display_id": "1711_6976", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "PARTS TRADER LLC", "vendor_display_id": "1711_PARTS", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "RANGER LOCKSMITH INC.", "vendor_display_id": "1711_5480", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "ROMEOVILLE TOYOTA", "vendor_display_id": "1711_ROMEOTOY", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "ROUTE ONE, LLC", "vendor_display_id": "1711_ROUTEONE", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "S & S AUTOMOTIVE INC", "vendor_display_id": "1711_5016", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SANDMAN PLUMBING", "vendor_display_id": "2315", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SCHAUMBURG FORD", "vendor_display_id": "1711_SFORD", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SCHAUMBURG HONDA", "vendor_display_id": "1711_52762", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SCHAUMBURG KIA", "vendor_display_id": "1711_155963", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SNAP-ON BUSINESS SOLUTIONS", "vendor_display_id": "1711_SNAP-ON", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SPORTWING INC", "vendor_display_id": "1711_8576", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SUBURBAN DOOR CHECK & LOCK", "vendor_display_id": "1711_5201", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SUBURBAN WHEEL COVER CO", "vendor_display_id": "1711_8688", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SUNBIT", "vendor_display_id": "2144", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SUPERIOR AUTO RECONDITIONING INC", "vendor_display_id": "2622", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "SUPERIOR SOUND INC", "vendor_display_id": "1711_5036", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "THE AUTOBARN", "vendor_display_id": "1711_6070", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "TIRE RACK WHOLESALE", "vendor_display_id": "1711_5394", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "TOP COVERAGE SOUTH INC", "vendor_display_id": "1711_7520", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "TOYOTA OF NAPERVILLE", "vendor_display_id": "1711_6047", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "TSD RENTAL LLC.", "vendor_display_id": "2102", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "UNITED RADIO SERVICE", "vendor_display_id": "1711_5107", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "US AUTO FORCE", "vendor_display_id": "1711_USAUTO", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "VARSITY VENDING", "vendor_display_id": "1711_VARSITY", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "VGP HOLDINGS, LLC", "vendor_display_id": "1711_5177", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "VITAL RECORDS CONTROL", "vendor_display_id": "1711_PROSHRED", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "WILDMAN FACILITY SERVICES", "vendor_display_id": "2623", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "WILLOWBROOK FORD", "vendor_display_id": "1711_6136", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "WINZER CORPORATION", "vendor_display_id": "1711_6137", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "XCITE AUTOMOTIVE/RECONLOGIC", "vendor_display_id": "1711_XCITE", "created_at": now},
        {"id": str(uuid.uuid4()), "dealer_id": "1711", "vendor_name": "ZEIGLER OF DOWNERS GROVE", "vendor_display_id": "1711_ZEIGLER", "created_at": now},
    ])


def downgrade() -> None:
    """Remove all seeded vendor mappings."""
    op.execute("DELETE FROM vendor_mappings")