"""add tekion_sessions table

Revision ID: e6b1ff9c4403
Revises: a1b2c3d4e5f6
Create Date: 2026-08-05 19:11:57.037746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e6b1ff9c4403'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tekion_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cookies', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('api_token', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('dealer_id', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('site_id', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('dealers_json', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tekion_sessions')
    # ### end Alembic commands ###
