"""add vin, document_type, severity to documents

Revision ID: f7201f6deb06
Revises: 5129f04c871e
Create Date: 2026-08-10 17:07:17.775574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7201f6deb06'
down_revision: Union[str, Sequence[str], None] = '5129f04c871e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('vin', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False, server_default=''))
    op.add_column('documents', sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_severity'), 'documents', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_severity'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_column('documents', 'severity')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'vin')
    # ### end Alembic commands ###
